# Generated by Django 4.2.30 on 2026-04-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colony", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breeding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "female",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maternal_breedings",
                        to="colony.mouse",
                    ),
                ),
                (
                    "male",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sired_breedings",
                        to="colony.mouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Litter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("litter_date", models.DateField()),
                ("size", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "breeding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litters",
                        to="breeding.breeding",
                    ),
                ),
            ],
        ),
    ]
