# Generated by Django 4.2.30 on 2026-04-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeding", "0002_breeding_phase1"),
    ]

    operations = [
        migrations.AddField(
            model_name="breeding",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="litter",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="litter",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
