# Generated by Django 5.2.13 on 2026-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeding", "0008_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breeding",
            name="breeding_type",
            field=models.CharField(
                choices=[("pair", "Pair"), ("trio", "Trio"), ("custom", "Custom")],
                default="pair",
                max_length=20,
            ),
        ),
    ]
