# Generated by Django 5.2.13 on 2026-06-09 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0009_align_breeding_type_choices'),
        ('colony', '0016_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='breeding',
            index=models.Index(fields=['active', 'male'], name='breeding_active_male'),
        ),
        migrations.AddIndex(
            model_name='breeding',
            index=models.Index(fields=['active', 'female_1'], name='breeding_active_f1'),
        ),
        migrations.AddIndex(
            model_name='breeding',
            index=models.Index(fields=['active', 'female_2'], name='breeding_active_f2'),
        ),
    ]
