# Generated by Django 5.2.13 on 2026-07-10 03:55

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def align_workflow_status_flags(apps, schema_editor):
    Breeding = apps.get_model("breeding", "Breeding")
    Litter = apps.get_model("breeding", "Litter")

    now = timezone.now()
    Breeding.objects.filter(status="closed", active=True).update(active=False, archived_at=now)
    Litter.objects.filter(litter_status__in=["ended", "archived"], is_archived=False).update(
        is_archived=True,
        archived_at=now,
    )
    Litter.objects.filter(is_archived=True).exclude(litter_status__in=["ended", "archived"]).update(
        litter_status="ended",
        archived_at=now,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("breeding", "0010_breeding_breeding_active_male_and_more"),
        ("colony", "0024_cagemembership_colony_mouse_one_current_cage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(align_workflow_status_flags, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="breeding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("active", False),
                    models.Q(("status", "closed"), _negated=True),
                    _connector="OR",
                ),
                name="breeding_active_status_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="litter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_archived", False),
                        models.Q(
                            ("litter_status__in", ["ended", "archived"]), _negated=True
                        ),
                    ),
                    models.Q(
                        ("is_archived", True),
                        ("litter_status__in", ["ended", "archived"]),
                    ),
                    _connector="OR",
                ),
                name="litter_archive_status_consistent",
            ),
        ),
    ]
