# Generated by Django 5.2.13 on 2026-07-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breeding", "0011_breeding_breeding_active_status_consistent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="litter",
            name="end_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="litter",
            name="end_outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weaned_complete", "Weaning and pup registration complete"),
                    ("all_pups_died", "All pups died before weaning"),
                    ("record_error", "Litter record was entered in error"),
                    ("transferred", "Pups transferred outside this colony"),
                    ("not_tracked", "Pups intentionally not tracked individually"),
                    ("other", "Other documented outcome"),
                ],
                max_length=32,
            ),
        ),
    ]
