# Generated by Django 4.2.30 on 2026-04-14 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="details",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="object_repr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("move_cage", "Move Cage"),
                    ("import", "Import"),
                    ("record_litter", "Record Litter"),
                    ("wean", "Wean"),
                ],
                max_length=32,
            ),
        ),
    ]
