# Generated by Django 4.2.30 on 2026-04-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_auditlog_options_remove_auditlog_actor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("cage", "Cage"),
                            ("mouse", "Mouse"),
                            ("genotype", "Genotype"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("success", models.BooleanField(default=False)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("error_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
