# Generated by Django 4.2.30 on 2026-04-15 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_members(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    ProjectMembership = apps.get_model("core", "ProjectMembership")
    for project in Project.objects.all():
        for user in project.members.all():
            ProjectMembership.objects.get_or_create(
                project=project,
                user=user,
                defaults={"role": "manager"},
            )


def backwards_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_project_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("manager", "Manager"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("project__name", "user__username"),
                "unique_together": {("project", "user")},
            },
        ),
        migrations.RunPython(forwards_copy_members, backwards_noop),
    ]
