# Generated by Django 4.2.30 on 2026-04-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cage_id", models.CharField(max_length=64, unique=True)),
                ("room", models.CharField(blank=True, max_length=64)),
                ("rack", models.CharField(blank=True, max_length=64)),
                ("position", models.CharField(blank=True, max_length=64)),
                (
                    "cage_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("breeding", "Breeding"),
                            ("weaning", "Weaning"),
                            ("quarantine", "Quarantine"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("holding", "Holding"),
                            ("breeding", "Breeding"),
                            ("experiment", "Experiment"),
                            ("retired", "Retired"),
                        ],
                        default="holding",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("sanitizing", "Sanitizing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("cage_id",),
            },
        ),
        migrations.CreateModel(
            name="StrainLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_name", models.CharField(max_length=128, unique=True)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("mouse", "Mouse"),
                            ("rat", "Rat"),
                            ("other", "Other"),
                        ],
                        default="mouse",
                        max_length=20,
                    ),
                ),
                ("background", models.CharField(blank=True, max_length=128)),
                ("source", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("line_name",),
            },
        ),
        migrations.CreateModel(
            name="Mouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mouse_uid", models.CharField(max_length=64, unique=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("U", "Unknown")],
                        default="U",
                        max_length=1,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dead", "Dead"),
                            ("culled", "Culled"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("ear_tag", models.CharField(blank=True, max_length=64)),
                ("coat_color", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "current_cage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_mice",
                        to="colony.cage",
                    ),
                ),
                (
                    "dam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_from_dam",
                        to="colony.mouse",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mice",
                        to="core.project",
                    ),
                ),
                (
                    "sire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offspring_from_sire",
                        to="colony.mouse",
                    ),
                ),
                (
                    "strain_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mice",
                        to="colony.strainline",
                    ),
                ),
            ],
            options={
                "ordering": ("-birth_date", "mouse_uid"),
            },
        ),
        migrations.CreateModel(
            name="CageMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=128)),
                ("is_current", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="colony.cage",
                    ),
                ),
                (
                    "mouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cage_memberships",
                        to="colony.mouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date", "-created_at"),
            },
        ),
    ]
