# Generated by Django 4.2.30 on 2026-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colony", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cage",
            name="created_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouse",
            name="origin",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mouse",
            name="toe_tag",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="strainline",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="strainline",
            name="key_name",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
