# Generated by Django 4.2.30 on 2026-04-15 07:04

from django.db import migrations, models
import django.db.models.deletion


def backfill_strainline_names_and_genotype_summary(apps, schema_editor):
    StrainLine = apps.get_model("colony", "StrainLine")
    Mouse = apps.get_model("colony", "Mouse")
    MouseGenotype = apps.get_model("genotypes", "MouseGenotype")

    for line in StrainLine.objects.all():
        changed = False
        if not line.name:
            line.name = line.display_name or line.line_name
            changed = True
        if not line.short_name:
            line.short_name = line.key_name or line.display_name or line.line_name
            changed = True
        if not line.gene_or_locus and line.background:
            line.gene_or_locus = line.background
            changed = True
        if changed:
            line.save(update_fields=["name", "short_name", "gene_or_locus"])

    mice_with_legacy = {}
    for gt in MouseGenotype.objects.select_related("gene", "mouse").all().order_by("mouse_id", "-assay_date", "-id"):
        if gt.mouse_id not in mice_with_legacy:
            mice_with_legacy[gt.mouse_id] = []
        if len(mice_with_legacy[gt.mouse_id]) >= 3:
            continue
        locus = gt.gene.symbol if gt.gene_id else (gt.locus_name or "locus")
        z = gt.zygosity_display or "/".join([p for p in [gt.allele_1, gt.allele_2] if p])
        mice_with_legacy[gt.mouse_id].append(f"{locus}:{z}" if z else locus)

    for mouse in Mouse.objects.all():
        if mouse.genotype_summary:
            continue
        parts = mice_with_legacy.get(mouse.id, [])
        if not parts:
            continue
        summary = ", ".join(parts)
        mouse.genotype_summary = f"{summary}..." if len(parts) == 3 else summary
        mouse.save(update_fields=["genotype_summary"])


class Migration(migrations.Migration):

    dependencies = [
        ("colony", "0002_cage_created_date_mouse_origin_mouse_toe_tag_and_more"),
        ("genotypes", "0002_gene_display_name_gene_is_active_gene_key_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouse",
            name="genotype_summary",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="strainline",
            name="category",
            field=models.CharField(
                choices=[
                    ("cre", "Cre"),
                    ("creERT2", "CreERT2"),
                    ("flox", "Flox"),
                    ("ko", "KO"),
                    ("ki", "KI"),
                    ("reporter", "Reporter"),
                    ("transgene", "Transgene"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="strainline",
            name="gene_or_locus",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="strainline",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="strainline",
            name="short_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="MouseGenotypeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("zygosity", models.CharField(blank=True, max_length=32)),
                ("allele_display_1", models.CharField(blank=True, max_length=64)),
                ("allele_display_2", models.CharField(blank=True, max_length=64)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "mouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genotype_components",
                        to="colony.mouse",
                    ),
                ),
                (
                    "strain_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouse_components",
                        to="colony.strainline",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.RunPython(backfill_strainline_names_and_genotype_summary, migrations.RunPython.noop),
    ]
