# Generated by Django 4.2.30 on 2026-04-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colony", "0003_mouse_genotype_summary_strainline_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cage",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mouse",
            name="death_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mouse",
            name="euthanasia_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cage",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("sanitizing", "Sanitizing"),
                    ("retired", "Retired"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mouse",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("dead", "Dead"),
                    ("culled", "Culled"),
                    ("transferred", "Transferred"),
                    ("euthanized", "Euthanized"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
