# Generated by Django 5.2.13 on 2026-06-09 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0010_breeding_breeding_active_male_and_more'),
        ('colony', '0016_performance_indexes'),
        ('core', '0007_project_created_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mouse',
            index=models.Index(fields=['status', 'project'], name='colony_mouse_status_proj'),
        ),
        migrations.AddIndex(
            model_name='mouse',
            index=models.Index(fields=['status', 'strain_line'], name='colony_mouse_status_strain'),
        ),
        migrations.AddIndex(
            model_name='mouse',
            index=models.Index(fields=['status', 'current_cage'], name='colony_mouse_status_cage'),
        ),
    ]
