# Generated by Django 5.2.13 on 2026-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colony", "0018_strainline_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strainlinedocument",
            name="description_kind",
            field=models.CharField(
                choices=[
                    ("strain_line_info", "Strain line info"),
                    ("genotype_info", "Genotype info"),
                    ("husbandry", "Husbandry"),
                    ("genetics", "Genetics"),
                    ("colony_notes", "Colony notes"),
                    ("protocol", "Protocol"),
                    ("other", "Other"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=32,
            ),
        ),
    ]
