# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colony", "0019_alter_strainlinedocument_description_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="mouse",
            name="possible_dams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Candidate dams when the exact mother is unknown, for example trio breeding litters.",
                related_name="possible_offspring_from_dam",
                symmetrical=False,
                to="colony.mouse",
            ),
        ),
    ]
