# Generated by Django 5.2.13 on 2026-06-16 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_colonies(apps, schema_editor):
    Colony = apps.get_model("colony", "Colony")
    Mouse = apps.get_model("colony", "Mouse")
    Cage = apps.get_model("colony", "Cage")
    Project = apps.get_model("core", "Project")
    StrainLine = apps.get_model("colony", "StrainLine")

    project_names = dict(Project.objects.values_list("id", "name"))
    strain_names = dict(StrainLine.objects.values_list("id", "line_name"))
    colony_ids: dict[tuple[int, int], int] = {}

    def get_colony_id(project_id: int, strain_line_id: int) -> int:
        key = (project_id, strain_line_id)
        if key in colony_ids:
            return colony_ids[key]
        name = f"{project_names.get(project_id, 'Project')} / {strain_names.get(strain_line_id, 'Strain line')}"
        colony, _created = Colony.objects.get_or_create(
            project_id=project_id,
            strain_line_id=strain_line_id,
            defaults={"name": name},
        )
        if not colony.name:
            colony.name = name
            colony.save(update_fields=["name", "updated_at"])
        colony_ids[key] = colony.pk
        return colony.pk

    for mouse_id, project_id, strain_line_id in Mouse.objects.values_list("id", "project_id", "strain_line_id"):
        if project_id and strain_line_id:
            Mouse.objects.filter(pk=mouse_id).update(colony_id=get_colony_id(project_id, strain_line_id))

    for cage in Cage.objects.all().only("id"):
        mouse_rows = list(
            Mouse.objects.filter(current_cage_id=cage.pk)
            .exclude(project_id__isnull=True)
            .exclude(strain_line_id__isnull=True)
            .values_list("project_id", "strain_line_id")
            .distinct()
        )
        project_ids = {project_id for project_id, _strain_line_id in mouse_rows}
        update: dict[str, int] = {}
        if len(project_ids) == 1:
            update["project_id"] = next(iter(project_ids))
        if len(mouse_rows) == 1:
            project_id, strain_line_id = mouse_rows[0]
            update["colony_id"] = get_colony_id(project_id, strain_line_id)
        if update:
            Cage.objects.filter(pk=cage.pk).update(**update)


def reverse_populate_colonies(apps, schema_editor):
    Colony = apps.get_model("colony", "Colony")
    Mouse = apps.get_model("colony", "Mouse")
    Cage = apps.get_model("colony", "Cage")

    Mouse.objects.update(colony_id=None)
    Cage.objects.update(project_id=None, colony_id=None)
    Colony.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0010_breeding_breeding_active_male_and_more'),
        ('colony', '0020_mouse_possible_dams'),
        ('core', '0007_project_created_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Home project for this cage. Empty only when ownership cannot be inferred yet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cages', to='core.project'),
        ),
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colonies', to='core.project')),
                ('strain_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colonies', to='colony.strainline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('project__name', 'strain_line__line_name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='cage',
            name='colony',
            field=models.ForeignKey(blank=True, help_text='Optional default colony for this cage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cages', to='colony.colony'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='colony',
            field=models.ForeignKey(blank=True, help_text='Actual project-specific colony/stock this mouse belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mice', to='colony.colony'),
        ),
        migrations.RunPython(populate_colonies, reverse_populate_colonies),
        migrations.AddIndex(
            model_name='cage',
            index=models.Index(fields=['status', 'project'], name='colony_cage_status_proj'),
        ),
        migrations.AddIndex(
            model_name='cage',
            index=models.Index(fields=['status', 'colony'], name='colony_cage_status_colony'),
        ),
        migrations.AddIndex(
            model_name='mouse',
            index=models.Index(fields=['status', 'colony'], name='colony_mouse_status_colony'),
        ),
        migrations.AddIndex(
            model_name='colony',
            index=models.Index(fields=['status', 'project'], name='colony_colony_status_proj'),
        ),
        migrations.AddIndex(
            model_name='colony',
            index=models.Index(fields=['status', 'strain_line'], name='colony_colony_status_strain'),
        ),
        migrations.AddConstraint(
            model_name='colony',
            constraint=models.UniqueConstraint(fields=('project', 'strain_line'), name='colony_unique_project_strain'),
        ),
    ]
