# Generated by Codex on 2026-06-18

import re

from django.db import migrations


NEW_VALUES = {
    "ko_null",
    "floxed_allele",
    "knock_in",
    "cre_ki",
    "cre_ert2_ki",
    "transgene",
    "reporter_knock_in",
    "reporter_transgene",
    "point_variant",
    "other_custom",
}


def _normalize_locus_type(raw_type: str, *, locus_name: str = "", line_name: str = "") -> str:
    value = (raw_type or "").strip()
    if value in NEW_VALUES:
        return value

    context = f"{locus_name or ''} {line_name or ''}".strip()
    context_lower = context.lower()
    context_compact = re.sub(r"[^a-z0-9]+", "", context_lower)

    if value == "x_linked":
        return "other_custom"
    if value == "flox":
        return "floxed_allele"
    if value == "reporter_ki":
        return "reporter_knock_in"
    if value == "tg_pos_neg":
        return "transgene"
    if value == "standard_autosomal":
        if re.search(r"(^|[^a-z0-9])(ko|null|knockout)([^a-z0-9]|$)", context_lower):
            return "ko_null"
        return "other_custom"
    if value == "cre_transgene":
        if "creert2" in context_compact:
            return "cre_ert2_ki"
        if re.search(r"(^|[^a-z0-9])(tg|transgene)([^a-z0-9]|$)", context_lower):
            return "transgene"
        return "cre_ki"

    aliases = {
        "ko": "ko_null",
        "knockout": "ko_null",
        "null": "ko_null",
        "ki": "knock_in",
        "knock-in": "knock_in",
        "knock_in": "knock_in",
        "cre": "cre_ki",
        "cre_ki": "cre_ki",
        "creert2": "cre_ert2_ki",
        "creert2_ki": "cre_ert2_ki",
        "tg": "transgene",
        "transgene": "transgene",
        "reporter": "reporter_knock_in",
        "reporter_tg": "reporter_transgene",
        "variant": "point_variant",
        "point_mutation": "point_variant",
        "custom": "other_custom",
        "other": "other_custom",
    }
    return aliases.get(value, "other_custom")


def _line_label(line) -> str:
    return (
        getattr(line, "name", "")
        or getattr(line, "display_name", "")
        or getattr(line, "line_name", "")
        or ""
    )


def forwards(apps, schema_editor):
    StrainLine = apps.get_model("colony", "StrainLine")
    for line in StrainLine.objects.all().only(
        "id",
        "line_name",
        "display_name",
        "name",
        "expected_loci_config",
    ):
        cfg = line.expected_loci_config
        if not isinstance(cfg, list):
            continue
        changed = False
        migrated = []
        line_label = _line_label(line)
        for raw in cfg:
            if not isinstance(raw, dict):
                migrated.append(raw)
                continue
            row = dict(raw)
            old_type = str(row.get("locus_type", "") or "").strip()
            new_type = _normalize_locus_type(
                old_type,
                locus_name=str(row.get("locus_name", "") or ""),
                line_name=line_label,
            )
            if new_type != old_type:
                row["locus_type"] = new_type
                changed = True
            migrated.append(row)
        if changed:
            line.expected_loci_config = migrated
            line.save(update_fields=["expected_loci_config"])


def backwards(apps, schema_editor):
    StrainLine = apps.get_model("colony", "StrainLine")
    reverse_map = {
        "ko_null": "standard_autosomal",
        "floxed_allele": "flox",
        "knock_in": "reporter_ki",
        "cre_ki": "cre_transgene",
        "cre_ert2_ki": "cre_transgene",
        "transgene": "tg_pos_neg",
        "reporter_knock_in": "reporter_ki",
        "reporter_transgene": "tg_pos_neg",
        "point_variant": "custom",
        "other_custom": "custom",
    }
    for line in StrainLine.objects.all().only("id", "expected_loci_config"):
        cfg = line.expected_loci_config
        if not isinstance(cfg, list):
            continue
        changed = False
        reverted = []
        for raw in cfg:
            if not isinstance(raw, dict):
                reverted.append(raw)
                continue
            row = dict(raw)
            old_type = str(row.get("locus_type", "") or "").strip()
            new_type = reverse_map.get(old_type)
            if new_type and new_type != old_type:
                row["locus_type"] = new_type
                changed = True
            reverted.append(row)
        if changed:
            line.expected_loci_config = reverted
            line.save(update_fields=["expected_loci_config"])


class Migration(migrations.Migration):
    dependencies = [
        ("colony", "0021_cage_project_colony_cage_colony_mouse_colony_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
