# Generated by Django 5.2.13 on 2026-07-10 03:55

import re
from django.db import migrations, models
from django.utils import timezone


def clean_memberships_and_genotype_components(apps, schema_editor):
    CageMembership = apps.get_model("colony", "CageMembership")
    Mouse = apps.get_model("colony", "Mouse")
    MouseGenotypeComponent = apps.get_model("colony", "MouseGenotypeComponent")

    duplicate_mouse_ids = (
        CageMembership.objects.filter(is_current=True)
        .values("mouse_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .values_list("mouse_id", flat=True)
    )
    today = timezone.localdate()
    current_cage_by_mouse = dict(
        Mouse.objects.filter(pk__in=duplicate_mouse_ids).values_list("pk", "current_cage_id")
    )
    for mouse_id in duplicate_mouse_ids.iterator():
        rows = list(
            CageMembership.objects.filter(mouse_id=mouse_id, is_current=True)
            .order_by("-start_date", "-created_at", "-pk")
        )
        preferred_cage_id = current_cage_by_mouse.get(mouse_id)
        keeper = next((row for row in rows if row.cage_id == preferred_cage_id), rows[0])
        for row in rows:
            if row.pk == keeper.pk:
                continue
            row.is_current = False
            row.end_date = max(row.start_date, today)
            row.reason = "Closed duplicate current membership during integrity migration"
            row.save(update_fields=["is_current", "end_date", "reason", "updated_at"])

    components_by_key = {}
    components = MouseGenotypeComponent.objects.order_by("mouse_id", "-updated_at", "-pk")
    for component in components.iterator():
        display_locus = " ".join((component.locus_name or "").strip().split())
        locus_key = re.sub(
            r"(?:\s+(?:flox|fl|ko|ki|reporter|transgene|knockout|knock-in))+$",
            "",
            display_locus,
            flags=re.IGNORECASE,
        ).strip().casefold()
        if component.locus_name != display_locus or component.locus_key != locus_key:
            component.locus_name = display_locus
            component.locus_key = locus_key
            component.save(update_fields=["locus_name", "locus_key", "updated_at"])
        if not locus_key:
            continue
        key = (component.mouse_id, locus_key)
        keeper = components_by_key.get(key)
        if keeper is None:
            components_by_key[key] = component
            continue
        keeper_has_result = bool(
            (keeper.zygosity or "").strip()
            or (keeper.allele_display_1 or "").strip()
            or (keeper.allele_display_2 or "").strip()
        )
        component_has_result = bool(
            (component.zygosity or "").strip()
            or (component.allele_display_1 or "").strip()
            or (component.allele_display_2 or "").strip()
        )
        if component_has_result and not keeper_has_result:
            keeper.zygosity = component.zygosity
            keeper.allele_display_1 = component.allele_display_1
            keeper.allele_display_2 = component.allele_display_2
            keeper.zygosity_class = component.zygosity_class
            keeper.chromosome_type = component.chromosome_type
            keeper.notes = component.notes
            keeper.save(
                update_fields=[
                    "zygosity",
                    "allele_display_1",
                    "allele_display_2",
                    "zygosity_class",
                    "chromosome_type",
                    "notes",
                    "updated_at",
                ]
            )
        component.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("colony", "0023_mouseexperimentassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mousegenotypecomponent",
            name="locus_key",
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.RunPython(clean_memberships_and_genotype_components, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cagemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("mouse",),
                name="colony_mouse_one_current_cage",
            ),
        ),
        migrations.AddConstraint(
            model_name="mousegenotypecomponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("locus_key", ""), _negated=True),
                fields=("mouse", "locus_key"),
                name="colony_mouse_locus_unique_ci",
            ),
        ),
    ]
