# Generated by Django 4.2.30 on 2026-04-14 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colony", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=64, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("symbol",),
            },
        ),
        migrations.CreateModel(
            name="MouseGenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locus_name", models.CharField(blank=True, max_length=128)),
                ("allele_1", models.CharField(blank=True, max_length=128)),
                ("allele_2", models.CharField(blank=True, max_length=128)),
                ("zygosity_display", models.CharField(blank=True, max_length=128)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("assay_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "gene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouse_genotypes",
                        to="genotypes.gene",
                    ),
                ),
                (
                    "mouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genotypes",
                        to="colony.mouse",
                    ),
                ),
            ],
            options={
                "ordering": ("-assay_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Allele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allele_name", models.CharField(max_length=128)),
                (
                    "allele_type",
                    models.CharField(
                        choices=[
                            ("wt", "Wild type"),
                            ("ko", "Knockout"),
                            ("ki", "Knock-in"),
                            ("tg", "Transgene"),
                            ("conditional", "Conditional"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alleles",
                        to="genotypes.gene",
                    ),
                ),
            ],
            options={
                "ordering": ("gene__symbol", "allele_name"),
            },
        ),
        migrations.AddConstraint(
            model_name="mousegenotype",
            constraint=models.UniqueConstraint(
                fields=("mouse", "gene", "locus_name"),
                name="uniq_mouse_gene_locus_genotype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="allele",
            unique_together={("gene", "allele_name")},
        ),
    ]
