# Generated by Django 4.2.30 on 2026-04-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genotypes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gene",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gene",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gene",
            name="key_name",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
